catalog:
  '@antfu/eslint-config': ^6.4.2
  '@storybook/addon-a11y': ^10.1.4
  '@storybook/addon-links': ^10.1.4
  '@storybook/vue3': ^10.1.4
  '@storybook/vue3-vite': ^10.1.4
  '@types/node': ^24.10.1
  '@vitejs/plugin-vue': ^6.0.2
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  eslint: ^9.39.1
  jsdom: ^27.2.0
  storybook: ^10.1.4
  typescript: ^5.9.3
  vite: ^7.2.6
  vitest: ^4.0.15
  vue: ^3.5.25
  vue-tsc: ^3.1.6

catalogMode: prefer

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - esbuild

shellEmulator: true

trustPolicy: no-downgrade
